#!/bin/bash
BASH_BOX_INSTALL_URL="https://raw.githubusercontent.com/simcu/bash-box/master/core/"
echo "Start Install Bash Box ....."
echo "Create system folder ....."
rm -rf ~/.bash_box/core
mkdir -p ~/.bash_box/core
if test ! -d ~/.bash_box/plugins;then
	mkdir ~/.bash_box/plugins
fi
if test ! -d ~/.bash_box/themes;then
	mkdir ~/.bash_box/themes
fi
echo "Download BashBox script ...."
curl -o ~/.bash_box/core/bb ${BASH_BOX_INSTALL_URL}bb
curl -o ~/.bash_box/core/init ${BASH_BOX_INSTALL_URL}init 
curl -o ~/.bash_box/core/prompt ${BASH_BOX_INSTALL_URL}prompt
curl -o ~/.bash_box/core/version ${BASH_BOX_INSTALL_URL}version
# unset BASH_BOX_INSTALL_URL	

# if test -f ~/.bash_profile;then
# else
	
# fi