#!/bin/bash
BASH_BOX_VERSION=$(cat ~/.bash_box/version)

# Load the bash box theme
if -e ~/.bash_box/themes/bb_actived
then
	source ~/.bash_box/themes/bb_actived
else	
	source ~/.bash_box/core/prompt
fi
load
unset desc
unset author

# Load the bash box core