#!/bin/bash
BASH_BOX_HOME=~/.bash_box
BASH_BOX_VERSION=$(cat ${BASH_BOX_HOME}/core/version)

# Load the bash box theme
if test -e ~/.bash_box/themes/bb_actived;then
	source ~/.bash_box/themes/bb_actived
else	
	source ~/.bash_box/core/prompt
fi
load
unset desc
unset author

# Load the bash box core
source ${BASH_BOX_HOME}/core/bb

# Load all the plugins
filelist=`ls ${BASH_BOX_HOME}/plugins`
for file in $filelist
do 
	source ${BASH_BOX_HOME}/plugins/$file
done